on:
  push:
    branches:
      - main
name: Publish
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp-julesroy.alwaysdata.net
          username: julesroy
          password: Jr040104#
          local-dir: ../